<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chun Su">
<meta name="dcterms.date" content="2022-02-28">

<title>Learning with sckinta - Interpreting the coefficients of Generalized Linear Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Learning with sckinta</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../posts.html">Posts</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../talks.html">Talks</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://sckinta.github.io/datadrivencv_cs/cv_render">CV</a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link active" data-scroll-target="#linear-regression">Linear regression</a>
  <ul class="collapse">
  <li><a href="#multivariate-linear-regression" id="toc-multivariate-linear-regression" class="nav-link" data-scroll-target="#multivariate-linear-regression">Multivariate linear regression</a></li>
  <li><a href="#with-interaction-term" id="toc-with-interaction-term" class="nav-link" data-scroll-target="#with-interaction-term">With interaction term</a></li>
  </ul></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">Logistic regression</a>
  <ul class="collapse">
  <li><a href="#when-y-is-binomial" id="toc-when-y-is-binomial" class="nav-link" data-scroll-target="#when-y-is-binomial">When Y is binomial</a></li>
  <li><a href="#multinominal-predictors" id="toc-multinominal-predictors" class="nav-link" data-scroll-target="#multinominal-predictors">Multinominal predictors</a></li>
  <li><a href="#contrasts-matrix" id="toc-contrasts-matrix" class="nav-link" data-scroll-target="#contrasts-matrix">Contrasts matrix</a></li>
  <li><a href="#multinomial-outcome" id="toc-multinomial-outcome" class="nav-link" data-scroll-target="#multinomial-outcome">Multinomial outcome</a></li>
  </ul></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression">Poisson regression</a></li>
  <li><a href="#final-remarks" id="toc-final-remarks" class="nav-link" data-scroll-target="#final-remarks">Final remarks</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Interpreting the coefficients of Generalized Linear Model</h1>
  <div class="quarto-categories">
    <div class="quarto-category">R</div>
    <div class="quarto-category">GLM</div>
    <div class="quarto-category">tidymodels</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Chun Su </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 28, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<p>Linear model is the most popular model used in various of fields, due to its simple execution and interpretation. It can be not only used to predict like all other machine learning models. but also widely used for statistical inference due to its simplicity.</p>
<p><a href="https://en.wikipedia.org/wiki/Generalized_linear_model">Generalized Linear Model (GLM)</a>, as named indicated, is generalized from linear regression model, and extends linear model default assumptions to include outcome variables following exponential family distribution. It used <a href="https://www.statisticshowto.com/link-function/#:~:text=A%20link%20function%20in%20a,variable%20in%20a%20linear%20way.">link function</a> to transform the outcome so that the transformed Y can be represented by linear combination of predictors. Due to this transformation, it makes coefficients interpretation a little confusing. In this blog, I will use four classical examples (<code>Boston</code>, <code>Default</code>, <code>BrainCancer</code>, and <code>Bikeshare</code> from <a href="https://cran.r-project.org/web/packages/ISLR2/ISLR2.pdf"><code>ISLR2</code></a> package) to illustrate how to interpret the coefficients of GLM from <code>tidymodels</code> fit tidy outcome in R.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression">Linear regression</h2>
<p>Modeling linear regression in R is simple. The following example used <code>dis</code> (weighted mean of distances to five Boston employment centers) as single predictor to predict <code>medv</code> (median value of house in $1000s) in Boston.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Boston)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>lm_m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(medv <span class="sc">~</span> dis, <span class="at">data =</span> Boston)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ dis, data = Boston)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.016  -5.556  -1.865   2.288  30.377 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  18.3901     0.8174  22.499  &lt; 2e-16 ***
dis           1.0916     0.1884   5.795 1.21e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 8.914 on 504 degrees of freedom
Multiple R-squared:  0.06246,   Adjusted R-squared:  0.0606 
F-statistic: 33.58 on 1 and 504 DF,  p-value: 1.207e-08</code></pre>
</div>
</div>
<p>Based on coefficients summary, <code>dis</code> is significantly (p-value = 1.21e-08) positively correlated with <code>medv</code>. With 1 unit increase in term of distances to Boston employment centers, the median value of house increase $1091.6 = 1.0916 * 1000.</p>
<section id="multivariate-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="multivariate-linear-regression">Multivariate linear regression</h3>
<p>In multivariate linear regression, when we interpret the coefficients, there are two components taken into account - whether the variables are independent - how to interpret the interaction term</p>
<p>In the following example, we model the <code>medv</code> with <code>dis</code> (weighted mean of distances to five Boston employment centers), <code>rm</code> (average number of rooms per dwelling), <code>crim</code> (per capita crime rate by town) and <code>chas</code> (tract bounds river).</p>
<p>For practice purpose, I will use <code>tidymodels</code> to build linear model in the multivariate linear regression example.</p>
<section id="no-interaction-term" class="level4">
<h4 class="anchored" data-anchor-id="no-interaction-term">No interaction term</h4>
<p>We starts with no interactions among the predictors.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>lm_spec2 <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_engine</span>(<span class="st">'lm'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_mode</span>(<span class="st">'regression'</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>lm_wf2 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_model</span>(lm_spec2) <span class="sc">%&gt;%</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_formula</span>(medv <span class="sc">~</span> dis <span class="sc">+</span> rm <span class="sc">+</span> crim <span class="sc">+</span> chas)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>lm_fit2 <span class="ot">&lt;-</span> lm_wf2 <span class="sc">%&gt;%</span> </span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit</span>(<span class="at">data =</span> Boston)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>lm_fit2 <span class="sc">%&gt;%</span> </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)  -29.1      2.57      -11.3  1.20e-26
2 dis            0.201    0.144       1.40 1.62e- 1
3 rm             8.19     0.406      20.2  9.12e-67
4 crim          -0.243    0.0350     -6.94 1.19e-11
5 chas           3.98     1.10        3.63 3.10e- 4</code></pre>
</div>
</div>
<p>In this model, all predictors except <code>dis</code> show significant correlation with <code>medv</code> (p-value &lt; 0.05). <code>rm</code> and <code>chas</code> are positively while <code>crim</code> is negatively associated with <code>medv</code>. - <code>rm</code>: <strong>when keeping all other variables the same</strong>, increase 1 room per dwelling on average results in $8,194.4 (<code>8.1944 * 1000</code>) increase in median house value. - <code>chas</code>: <strong>when keeping all other variables the same</strong>, having tracts bounds to the Charles river increase median house value $3,982.5 (<code>3.9825 * 1000</code>). <code>chas</code> is a dummy variable where = 1 if tract bounds river and =0 otherwise. Thus =0 (tract do not bound to river) is a baseline here. We will discuss more about baseline in later example. - <code>crim</code>: <strong>when keeping all other variables the same</strong>, 1 unit increase in per capita crime rate will result a decrease of $243.2 (<code>-0.24318 * 1000</code>) in median house value.</p>
</section>
</section>
<section id="with-interaction-term" class="level3">
<h3 class="anchored" data-anchor-id="with-interaction-term">With interaction term</h3>
<p>Based on common sense, usually the house is smaller when it is closer to city center. Adding interaction term between <code>rm</code> and <code>dis</code> we assumed that the number of room and the distance to business center are not independent. We are testing the hypothesis that the linear relationship between <code>dis</code> and <code>medv</code> was affected by the the <code>rm</code>. This affect can be linear or non-linear, can be negative or positive.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Boston <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(rm)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'mean number of room per dwelling'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="2022-02-28-glm_coefficients_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Boston <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">rm =</span> <span class="fu">as.integer</span>(rm)) <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>dis, <span class="at">y=</span>medv, <span class="at">color=</span><span class="fu">as.factor</span>(rm))) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> F) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'mean of distances to five Boston employment centers'</span>, <span class="at">y=</span> <span class="st">'median value of owner-occupied homes'</span>, <span class="at">color=</span><span class="st">"mean number of room per dwelling"</span>) <span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">'bottom'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="2022-02-28-glm_coefficients_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Thus, we added interaction term between <code>dis</code> and <code>rm</code>. The thumb of rule to use interaction term is hierarchical principle, which means, if we include an interaction in a model, we should also include the main effects, even if the p-values associated with main effect coefficients are not significant. Thus we should always use <code>*</code> instead of <code>:</code> when adding the interaction term. <code>dis*rm</code> means <code>dis + rm + dis:rm</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>lm_wf3 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_model</span>(lm_spec2) <span class="sc">%&gt;%</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_formula</span>(medv <span class="sc">~</span> dis<span class="sc">*</span>rm <span class="sc">+</span> crim <span class="sc">+</span> chas)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>lm_fit3 <span class="ot">&lt;-</span> lm_wf3 <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit</span>(<span class="at">data =</span> Boston)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>lm_fit3 <span class="sc">%&gt;%</span> </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)   -5.03     4.70       -1.07 2.85e- 1
2 dis           -7.43     1.27       -5.84 9.30e- 9
3 rm             4.38     0.744       5.89 7.11e- 9
4 crim          -0.270    0.0341     -7.90 1.80e-14
5 chas           3.99     1.06        3.77 1.83e- 4
6 `dis:rm`       1.20     0.198       6.04 3.08e- 9</code></pre>
</div>
</div>
<p>In this example, all predictors including interaction terms are significant. Interestingly, by adding the interaction between <code>dis</code> and <code>rm</code>, the coefficients associated with <code>dis</code> turn negative from positive when using simple single variable model. To interpret the interaction term,</p>
<ul>
<li><code>dis:rm</code>: since interaction term is significant (p-value = 3.077938e-09), thus linear relationship between <code>dis</code> and <code>medv</code> was significantly dependent on the <code>rm</code>, justifying the inclusion of the interaction term in the model.</li>
<li><code>dis</code>: when there are 3 ~ 6 rooms in dwelling, one unit further away from five Boston employment centers, it results in $3,835 to $244 (<code>(-7.426 + range(3,6) * 1.197) * 1000</code>) decrease in median value of house. when there are more than 6 (<code>7.426/1.197</code>) rooms in dwelling, one unit further away from five Boston employment centers, it results in at least $953 (<code>(-7.426 + 7 * 1.197) * 1000</code>) increase in median value of house.</li>
<li><code>rm</code>: <em>keeping the mean distance to five Boston employment centers as constant <code>dis</code></em>, one more room in dwelling will increase <code>1000 * (1.197 * dis + 4.380)</code> in the median value of house. Because the interaction term is positive (<code>1.197</code>), the rate of <code>medv</code> increase in terms of the room number will increase when it is further away from Boston employment centers.</li>
</ul>
<section id="when-to-use-interaction-term" class="level5">
<h5 class="anchored" data-anchor-id="when-to-use-interaction-term">When to use interaction term</h5>
<p>The frequently asked question about interaction term is “when should we include interaction term”. The conventional answer is when two predictors are not independent. However, in reality, unless we have very strong prior knowledge about the predictors, it is hard to determine whether two predictors are dependent or not without exploring the data. From the articles/blogs about interaction term I read so far, two methods are generally used to determine whether add interaction term</p>
<ol type="1">
<li><p>try both with and without adding interaction term, if adding interaction term results in significance on interaction term, then use interaction term.</p></li>
<li><p>like what I did above, plot Y against X1 with X2 as nominal variable (if X2 is not nominal variable itself). If the lines from different X2 levels are parallel, then X1 and X2 are independent and no interaction terms are needed. Otherwise, add interaction term.</p></li>
</ol>
</section>
</section>
</section>
<section id="logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="logistic-regression">Logistic regression</h2>
<p>In the regular linear regression mentioned above, the Y is numeric (aka. quantitative). However, when Y is nominal (aka, qualitative), logistic regression will be used. To make Y still represented by linear combination of predictors, we used logit function (link function) to transform Y (the probability) to <span class="math inline">\(ln(\frac{p}{1-p})\)</span> (the log odds).</p>
<p><span class="math display">\[ln(\frac{p}{1-p}) = \sum\beta X\]</span> <span class="math inline">\(\beta\)</span> represents log odds ratio. thus, odds ratio <span class="math inline">\(OR = e^\beta\)</span>.</p>
<section id="when-y-is-binomial" class="level3">
<h3 class="anchored" data-anchor-id="when-y-is-binomial">When Y is binomial</h3>
<p>To evaluate whether a customer will default the credit card <code>default</code>, we build a logistic model with three predictors – whether the customer is a <code>student</code>, the <code>balance</code> on the account and the customer <code>income</code>.</p>
<p>Again, for practice purpose, I used <code>tidymodels</code> syntax for demonstration.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Default"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>lr_spec <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_engine</span>(<span class="st">'glm'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_mode</span>(<span class="st">'classification'</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>default_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_model</span>(lr_spec) <span class="sc">%&gt;%</span> </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_formula</span>(default <span class="sc">~</span> .)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>default_fit <span class="ot">&lt;-</span> default_wf <span class="sc">%&gt;%</span> </span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit</span>(<span class="at">data =</span> Default)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>default_fit <span class="sc">%&gt;%</span> </span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term            estimate  std.error statistic   p.value
  &lt;chr&gt;              &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept) -10.9        0.492        -22.1   4.91e-108
2 studentYes   -0.647      0.236         -2.74  6.19e-  3
3 balance       0.00574    0.000232      24.7   4.22e-135
4 income        0.00000303 0.00000820     0.370 7.12e-  1</code></pre>
</div>
</div>
<p>In this model, two predictors (<code>student</code> and <code>balance</code>) are significantly associated with <code>default</code>. To interpret coefficients, we first need to know which is the baseline of <code>default</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(Default<span class="sc">$</span>default)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    Yes
No    0
Yes   1</code></pre>
</div>
</div>
<p>Based on the <code>contrasts</code> output, the baseline of <code>default</code> is <code>No</code>. Thus,</p>
<ul>
<li><p><code>student</code>: <strong>When keeping all other variable constant</strong>, compared to non-student (<code>student = 0</code>), a student (<code>student = 1</code>) is less likely to default credit card. The odds ratio is 0.524 (<code>exp(-6.467758e-01)</code>). In other words, if the odds of defaulting credit card as non-student is 1, the odds of defaulting credit card as a student is 0.524 (<code>exp(-6.467758e-01)</code>).</p></li>
<li><p><code>balance</code>: <strong>When keeping all other variable constant</strong>, 1 dollar increase in account balance will result in increasing odds of 1.005 (<code>exp(5.736505e-03)</code>) to default credit card.</p></li>
</ul>
<p>Note: above modeling is a bad model since there are high correlation between the predictors (<a href="https://www.britannica.com/topic/collinearity-statistics">collinearity</a>). I just used it as an example to interpret the coefficients.</p>
</section>
<section id="multinominal-predictors" class="level3">
<h3 class="anchored" data-anchor-id="multinominal-predictors">Multinominal predictors</h3>
<p>Using multi-nominal predictor <code>diagnosis</code> and other predictors like <code>sex</code> and age <code>time</code> to predict whether the patient survived the brain cancer or not <code>status</code></p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">'BrainCancer'</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>BrainCancer <span class="ot">&lt;-</span> BrainCancer <span class="sc">%&gt;%</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">na.omit</span>()</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(BrainCancer<span class="sc">$</span>diagnosis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           LG glioma HG glioma Other
Meningioma         0         0     0
LG glioma          1         0     0
HG glioma          0         1     0
Other              0         0     1</code></pre>
</div>
</div>
<p>In this example, <code>Meningioma</code> is the baseline for multi-nominal predictor <code>diagnosis</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>BrainCancer_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(status <span class="sc">~</span> ., <span class="at">data =</span> BrainCancer) <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_mutate</span>(<span class="at">status =</span> <span class="fu">as.factor</span>(status)) <span class="sc">%&gt;%</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_dummy</span>(diagnosis)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>BrainCancer_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_model</span>(lr_spec) <span class="sc">%&gt;%</span> </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_recipe</span>(BrainCancer_rec)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>BrainCancer_fit <span class="ot">&lt;-</span> BrainCancer_wf <span class="sc">%&gt;%</span> </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit</span>(<span class="at">data =</span> BrainCancer)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>BrainCancer_fit <span class="sc">%&gt;%</span> </span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   term                estimate std.error statistic p.value
   &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1 (Intercept)           3.56      2.57       1.39  0.166  
 2 sexMale               0.369     0.576      0.640 0.522  
 3 locSupratentorial     1.09      0.901      1.21  0.227  
 4 ki                   -0.0695    0.0326    -2.13  0.0332 
 5 gtv                   0.0382    0.0366     1.04  0.296  
 6 stereoSRT             0.253     0.771      0.328 0.743  
 7 time                 -0.0339    0.0155    -2.18  0.0291 
 8 diagnosis_LG.glioma   1.31      0.844      1.55  0.122  
 9 diagnosis_HG.glioma   2.37      0.778      3.05  0.00231
10 diagnosis_Other       0.765     0.940      0.814 0.416  </code></pre>
</div>
</div>
<p>For multi-nominal predictor <code>diagnosis</code>, the levels (<code>LG glioma</code>, <code>HG glioma</code> and <code>Other</code>) are compared to the baseline <code>Meningioma</code>, and it ends with three terms for coefficient estimation.</p>
<p>Based on above model, only <code>HG glioma</code> show significant association with survival (p-value &lt; 0.05) when choose <code>Meningioma</code> as baseline. <strong>When keeping all other variable constant</strong>, compare to <code>Meningioma</code>, the patient with <code>HG glioma</code> are 10 times more (<code>exp(2.37027243)</code>) likely to survive. If we want to compare <code>HG glioma</code> with <code>Other</code> cancer type, simply use <code>exp(2.37027243-0.76482440)</code> to get odds ratio between <code>HG glioma</code> and <code>Other</code>, in which compare to <code>Other</code>, the patient with <code>HG glioma</code> are 5 times more (<code>exp(2.37027243-0.76482440)</code>) likely to survive. However, in this case, we do not know whether this comparison is statistically significant. We can get p-value for this comparison by switching <code>Other</code> as baseline.</p>
</section>
<section id="contrasts-matrix" class="level3">
<h3 class="anchored" data-anchor-id="contrasts-matrix">Contrasts matrix</h3>
<p>Another baseline assignment is using the global average as baseline. To do that, we need to change the <code>contrasts</code> matrix. The following code replace the default contrasts <code>contr.treatment</code> with <code>contr.sum</code> on <code>globalOptions</code>, then use <code>step_dummy</code> from <code>recipe</code> to realize it</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>BrainCancer_rec <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prep</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bake</span>(<span class="at">new_data =</span> <span class="cn">NULL</span>, <span class="fu">starts_with</span>(<span class="st">"diagnosis"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">diagnosis_orginal =</span> BrainCancer<span class="sc">$</span>diagnosis) <span class="sc">%&gt;%</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">distinct</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  diagnosis_LG.glioma diagnosis_HG.glioma diagnosis_Other diagnosis_orginal
                &lt;dbl&gt;               &lt;dbl&gt;           &lt;dbl&gt; &lt;fct&gt;            
1                   0                   0               0 Meningioma       
2                   0                   1               0 HG glioma        
3                   1                   0               0 LG glioma        
4                   0                   0               1 Other            </code></pre>
</div>
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>contr_opt <span class="ot">&lt;-</span> <span class="fu">getOption</span>(<span class="st">"contrasts"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>contr_opt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        unordered           ordered 
"contr.treatment"      "contr.poly" </code></pre>
</div>
</div>
<p>The original baseline is <code>Meningioma</code>, each <code>diagnosis_</code> is compared to the <code>Meningioma</code>.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>contr_sum_opt <span class="ot">&lt;-</span> contr_opt</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>contr_sum_opt[<span class="st">'unordered'</span>] <span class="ot">&lt;-</span> <span class="st">'contr.sum'</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> contr_sum_opt)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># my_naming &lt;- function(var, lvl, ordinal = FALSE, sep = "_"){</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co">#     paste(var, levels(BrainCancer$diagnosis)[lvl])</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># }</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>BrainCancer_rec2 <span class="ot">&lt;-</span> <span class="fu">recipe</span>(status <span class="sc">~</span> ., <span class="at">data =</span> BrainCancer) <span class="sc">%&gt;%</span> </span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_mutate</span>(<span class="at">status =</span> <span class="fu">as.factor</span>(status)) <span class="sc">%&gt;%</span> </span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_dummy</span>(diagnosis)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>BrainCancer_rec2 <span class="sc">%&gt;%</span> </span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prep</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bake</span>(<span class="at">new_data =</span> <span class="cn">NULL</span>, <span class="fu">starts_with</span>(<span class="st">"diagnosis"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">diagnosis_orginal =</span> BrainCancer<span class="sc">$</span>diagnosis) <span class="sc">%&gt;%</span> </span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">distinct</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  diagnosis_X1 diagnosis_X2 diagnosis_X3 diagnosis_orginal
         &lt;dbl&gt;        &lt;dbl&gt;        &lt;dbl&gt; &lt;fct&gt;            
1            1            0            0 Meningioma       
2            0            0            1 HG glioma        
3            0            1            0 LG glioma        
4           -1           -1           -1 Other            </code></pre>
</div>
</div>
<p>Thus <code>diagnosis_X1</code>, <code>diagnosis_X2</code> and <code>diagnosis_X3</code> now represents <code>Meningioma</code>, <code>HG glioma</code> and <code>LG glioma</code> compared to average baseline.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>BrainCancer_wf2 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_recipe</span>(BrainCancer_rec2) <span class="sc">%&gt;%</span> </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_model</span>(lr_spec)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>BrainCancer_fit2 <span class="ot">&lt;-</span> BrainCancer_wf2 <span class="sc">%&gt;%</span> </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit</span>(<span class="at">data =</span> BrainCancer)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>BrainCancer_fit2 <span class="sc">%&gt;%</span> </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 5
   term         estimate std.error statistic p.value
   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
 1 (Intercept)    5.52      2.66       2.07   0.0380
 2 sex1          -0.184     0.288     -0.640  0.522 
 3 loc1          -0.545     0.451     -1.21   0.227 
 4 ki            -0.0695    0.0326    -2.13   0.0332
 5 gtv            0.0382    0.0366     1.04   0.296 
 6 stereo1       -0.127     0.386     -0.328  0.743 
 7 time          -0.0339    0.0155    -2.18   0.0291
 8 diagnosis_X1  -1.11      0.468     -2.37   0.0177
 9 diagnosis_X2   0.195     0.594      0.329  0.742 
10 diagnosis_X3   1.26      0.542      2.33   0.0200</code></pre>
</div>
</div>
<p>Based on the newly trained model <code>BrainCancer_fit2</code>, only <code>Meningioma</code> and <code>LG glioma</code> show significant association with survival (p-value &lt; 0.05) when compared to global average. <strong>When keeping all other variable constant</strong>, <strong>compare to global average</strong>, the patient with <code>Meningioma</code> has only 32.9% (<code>exp(-1.11018843)</code>) average survive rate, while the patient with <code>LG glioma</code> are 3.5 times (<code>exp(1.26008400)</code>) more likely to survive.</p>
<p>More about coding contrasts in base R syntax can be found at this <a href="https://marissabarlaz.github.io/portfolio/contrastcoding/">article</a>.</p>
</section>
<section id="multinomial-outcome" class="level3">
<h3 class="anchored" data-anchor-id="multinomial-outcome">Multinomial outcome</h3>
<p>Using the same dataset <code>BrainCancer</code>, now I try to predict the <code>diagnosis</code> based on the tumor location (<code>loc</code>), Karnofsky index (<code>ki</code>), Gross tumor volume (<code>gtv</code>) and Stereotactic method (<code>stereo</code>). Here we used <code>multinom_reg()</code> to model multinomial regression</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> contr_opt) <span class="co"># reset contrasts options back to `contr.treatment`</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>ml_spec <span class="ot">&lt;-</span> <span class="fu">multinom_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_engine</span>(<span class="st">'nnet'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_mode</span>(<span class="st">'classification'</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>BrainCancer_rec3 <span class="ot">&lt;-</span> <span class="fu">recipe</span>(diagnosis <span class="sc">~</span> loc <span class="sc">+</span> ki <span class="sc">+</span> gtv <span class="sc">+</span> stereo, <span class="at">data =</span> BrainCancer) <span class="sc">%&gt;%</span> </span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">update_role</span>(diagnosis, <span class="at">new_role =</span> <span class="st">'outcome'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>())</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>BrainCancer_wf3 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_model</span>(ml_spec) <span class="sc">%&gt;%</span> </span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_recipe</span>(BrainCancer_rec3)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>BrainCancer_fit3 <span class="ot">&lt;-</span> BrainCancer_wf3 <span class="sc">%&gt;%</span> </span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit</span>(<span class="at">data =</span> BrainCancer)</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>BrainCancer_fit3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow [trained] ══════════════════════════════════════════════════════════
Preprocessor: Recipe
Model: multinom_reg()

── Preprocessor ────────────────────────────────────────────────────────────────
2 Recipe Steps

• step_normalize()
• step_dummy()

── Model ───────────────────────────────────────────────────────────────────────
Call:
nnet::multinom(formula = ..y ~ ., data = data, trace = FALSE)

Coefficients:
          (Intercept)          ki         gtv loc_Supratentorial stereo_SRT
LG glioma  -2.3035689  0.23860763 -0.02596393          0.3998414  0.5444269
HG glioma  -2.5894735  0.03684929  0.15897113          0.9417737  1.3658683
Other      -0.4158848 -0.29780559  0.14203552         -2.7892771  1.4289732

Residual Deviance: 187.5196 
AIC: 217.5196 </code></pre>
</div>
</div>
<p>In the multinomial regression, no p-value were reported. The coefficients represent log odds ratio.</p>
<p>Each row in the coefficient table corresponds to the model equation. eg. the first row represents the coefficients for <code>LG glioma</code> in comparison to our baseline <code>Meningioma</code>. Each column in the coefficient table corresponds to specific coefficient estimate. Thus, compared to <code>Meningioma</code>, using <code>SRT</code> Stereotactic method is about 4 times (<code>exp(1.3658683)</code>) more likely diagnose <code>HG glioma</code>. A tumor is only 6% (<code>exp(-2.7892771)</code>) chance to be diagnosed as <code>Other</code> instead of <code>Meningioma</code> if it is located at <code>Supratentorial</code> area.</p>
<p>To perform above model in base R syntax, please refer to the <a href="https://datasciencebeginners.com/2018/12/20/multinomial-logistic-regression-using-r/#:~:text=Multinomial%20regression%20is%20an%20extension,one%20or%20more%20independent%20variable.">blog post</a> by Mohit Sharma.</p>
</section>
</section>
<section id="poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="poisson-regression">Poisson regression</h2>
<p>Poisson regression is used to model count outcome. Unlike regular linear regression, count outcome is not real continuous variable. Instead, it must be positive integer and usually modeled by Poisson distribution rather than normal distribution.</p>
<p>The link function for Poisson regression is log function <span class="math inline">\(\ln\lambda\)</span> where <span class="math inline">\(\lambda\)</span> represents the mean of outcome.</p>
<p>In the following example, we use <code>Bikeshare</code> data to predict <code>bikers</code> outcome which represents the <em>count</em> of rental bikers</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">'Bikeshare'</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>Bikeshare_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(bikers <span class="sc">~</span> season <span class="sc">+</span> weekday <span class="sc">+</span> weathersit <span class="sc">+</span> temp <span class="sc">+</span> hum <span class="sc">+</span> windspeed, <span class="at">data =</span> Bikeshare) <span class="sc">%&gt;%</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_num2factor</span>(season, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"winter"</span>,<span class="st">'spring'</span>,<span class="st">'summer'</span>,<span class="st">'fall'</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_num2factor</span>(weekday, <span class="at">transform =</span> <span class="cf">function</span>(x) {x<span class="sc">+</span><span class="dv">1</span>}, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'sunday'</span>,<span class="st">'monday'</span>,<span class="st">'tuesday'</span>,<span class="st">'wednesday'</span>,<span class="st">'thursday'</span>,<span class="st">'friday'</span>,<span class="st">'saturday'</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_normalize</span>(<span class="fu">all_numeric_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">I</span>()</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Bikeshare_rec %&gt;% prep() %&gt;% bake(new_data = NULL)</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(poissonreg)</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>pr_spec <span class="ot">&lt;-</span> <span class="fu">poisson_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_engine</span>(<span class="st">'glm'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_mode</span>(<span class="st">'regression'</span>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>Bikeshare_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_recipe</span>(Bikeshare_rec) <span class="sc">%&gt;%</span> </span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">add_model</span>(pr_spec)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>Bikeshare_fit <span class="ot">&lt;-</span> Bikeshare_wf <span class="sc">%&gt;%</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>     parsnip<span class="sc">::</span><span class="fu">fit</span>(Bikeshare)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>Bikeshare_fit <span class="sc">%&gt;%</span></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 5
   term                       estimate std.error statistic   p.value
   &lt;chr&gt;                         &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 (Intercept)                  4.58    0.00385   1191.    0        
 2 temp                         0.426   0.00149    285.    0        
 3 hum                         -0.256   0.00108   -238.    0        
 4 windspeed                    0.0404  0.000949    42.6   0        
 5 season_spring                0.302   0.00384     78.7   0        
 6 season_summer                0.144   0.00449     32.1   1.12e-226
 7 season_fall                  0.613   0.00345    177.    0        
 8 weekday_monday              -0.0464  0.00336    -13.8   1.82e- 43
 9 weekday_tuesday             -0.0405  0.00336    -12.1   1.42e- 33
10 weekday_wednesday           -0.0524  0.00342    -15.3   4.88e- 53
11 weekday_thursday            -0.0804  0.00339    -23.7   2.70e-124
12 weekday_friday              -0.0151  0.00335     -4.51  6.47e-  6
13 weekday_saturday            -0.0187  0.00336     -5.58  2.36e-  8
14 weathersit_cloudy.misty      0.106   0.00223     47.4   0        
15 weathersit_light.rain.snow  -0.163   0.00425    -38.4   0        
16 weathersit_heavy.rain.snow  -0.0368  0.167       -0.221 8.25e-  1</code></pre>
</div>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(Bikeshare<span class="sc">$</span>weathersit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                cloudy/misty light rain/snow heavy rain/snow
clear                      0               0               0
cloudy/misty               1               0               0
light rain/snow            0               1               0
heavy rain/snow            0               0               1</code></pre>
</div>
</div>
<p>All terms except <code>weathersit_heavy.rain.snow</code> are significantly associated with rental bikers number. - when keeping all other variables constant, compared to <code>season_winter</code>, <code>season_spring</code> will increase the mean of rental biker count by 1.35 <code>exp(0.30234965)</code>. In other words, there will be 135% bikers rental a bike in spring than winter. - when keeping all other variables constant, every unit increase in temperature will result in on average 1.53 (<code>exp(0.42588059)</code>) rental biker customer.</p>
<p><em>note:above model is not optimal model to predict rental bikers. We use the model without interactions to simplify the question and emphasize interpretation of coefficients in the context of poisson regression . To interpret the coefficients with interaction term, refer to previous regular linear regression example</em></p>
</section>
<section id="final-remarks" class="level2">
<h2 class="anchored" data-anchor-id="final-remarks">Final remarks</h2>
<p>In this post, I focus on interpret the coefficients in three GLM, and show the examples of coefficients associated with both quantitative and qualitative predictors. I also include the examples to interpret coefficients when 1) add interaction term, 2) with multi-nominal outcome and 3) with alternative contrast matrix.</p>


</section>

</main> <!-- /main -->
<div>

<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-size="large" data-hashtags="#rstats" data-show-count="false">Tweet</a><script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<div>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<script src="https://utteranc.es/client.js" repo="sckinta/blog_comments" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->



</div></div></body></html>